data:
  dataset: DAIR-V2X
  split: test
  data_info_path: data/data_info_top3000.json
  data_root: data/DAIR-V2X/cooperative-vehicle-infrastructure
  noise:
    pos_std: 0
    rot_std: 0
  max_samples: 3000
filters:
  top_k: 10
  distance_m: 120
  priority_categories: [bus, truck, car]
matching:
  strategy: ['category', 'core']
  core_components: ['centerpoint_distance', 'vertex_distance']
  filter_strategy: thresholdRetained
  filter_threshold: 4
  matches2extrinsic: weightedSVD
  svd_strategy: svd_with_match
  distance_thresholds:
    truck: 1.5
    van: 1.5
    bus: 1.5
    car: 1.0
    trafficcone: 0.5
    pedestrian: 0.5
    cyclist: 0.5
    motorcyclist: 0.5
    tricylist: 0.5
    barrawlist: 0.5
    detected: 1.0
  prior_weight: 0.0
  parallel_flag: false
  corresponding_parallel: false
solver:
  stability_gate: 0
  max_iterations: 1
evaluation:
  success_thresholds: [1.0, 2.0, 3.0, 4.0, 5.0]
  time_verbose: false
output:
  root_dir: outputs
  tag: null
